from Coordinates import Coordinates

COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_RED = (255, 0, 0)

WINDOW_SIZE_X = 800
WINDOW_SIZE_Y = 600
DEFAULT_SPEED = 1
DEFAULT_TRACKED_ASTEROIDS = 5
CENTER_POINT = Coordinates(WINDOW_SIZE_X/2, WINDOW_SIZE_Y/2)

ASTEROIDS_MAX_VELOCITY = 5
ASTEROIDS_POINTS_PER_HIT = 1000
ASTEROIDS_PER_SPAWN = 1
ASTEROIDS_SPAWN_INTERVAL = 1000
ASTEROIDS_MAX_ON_SCREEN = 5
DIFFICULTY_INCREASE_INTERVAL = 10000
SPAWN_INTERVAL_DECREASE = 20
SPAWN_MARGIN = 100

SPEED_AFTER_BOUNCE = 0.7

MAIN_BOOSTER_POWER = 0.09
SIDE_BOOSTER_POWER = 3 # in degrees
FIRE_POWER = 7
SLOW_DOWN_RATE = 0.01
MISSILE_RELOAD_TIME = 500
MAX_SPEED = 7
