#ifndef MACHINEGAMING_MUTATIONTYPE_H
#define MACHINEGAMING_MUTATIONTYPE_H

enum MutationType {
    ADD_NEURON,
    ADD_CONNECTION,
    DELETE_CONNECTION,
    DELETE_NEURON,
    RANDOMIZE_WEIGHT
};

#endif //MACHINEGAMING_MUTATIONTYPE_H
